version: '3.8'

services:
  frontend:
    build: ./todo-app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./todo-app/frontend:/app

  backend:
    build: ./todo-app/backend
    ports:
      - "5000:5000"
    env_file:
      - ./todo-app/backend/.env
    depends_on:
      - mongo
    # volumes:
    #   - ./todo-app/backend:/app

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: